-- MySQL Script generated by MySQL Workbench
-- dom 24 set 2023 13:50:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fone` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`contas_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`contas_pagar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(100) NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `total` DOUBLE(10,2) NOT NULL,
  `Fornecedores_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Fornecedores_id`),
  INDEX `fk_contas_pagar_Fornecedores1_idx` (`Fornecedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_contas_pagar_Fornecedores1`
    FOREIGN KEY (`Fornecedores_id`)
    REFERENCES `projeto`.`Fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`contas_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`contas_receber` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(100) NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `total` DOUBLE(10,2) NOT NULL,
  `Clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Clientes_id`),
  INDEX `fk_contas_receber_Clientes_idx` (`Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_contas_receber_Clientes`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `projeto`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
